create table if not exists public.orders (
  reference text primary key,
  stripe_session_id text unique,
  status text not null default 'pending',
  customer_email text,
  customer_name text,
  total_amount numeric(12, 2) not null default 0,
  currency text not null default 'EUR',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_reference text not null references public.orders(reference) on delete cascade,
  product_id text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null,
  total_amount numeric(12, 2) not null,
  currency text not null default 'EUR',
  created_at timestamptz not null default now(),
  unique (order_reference, product_id)
);

create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_customer_email_idx on public.orders(customer_email);
create index if not exists order_items_order_reference_idx on public.order_items(order_reference);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "service role manages orders" on public.orders;
create policy "service role manages orders"
on public.orders
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role manages order items" on public.order_items;
create policy "service role manages order items"
on public.order_items
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
