-- Modèle digital Bazario : profils utilisateurs + droits d'accès (entitlements).
-- Permet de relier un achat à un compte connecté et d'autoriser les téléchargements.

-- 1) Profils (1-1 avec auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  first_name text,
  last_name text,
  role text not null default 'buyer', -- 'buyer' | 'seller'
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Droits d'accès : un produit acheté par un utilisateur (licence + accès)
create table if not exists public.entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  customer_email text,                       -- repli si l'achat est fait sans compte
  product_slug text not null,
  product_title text not null,
  license_label text,
  stripe_session_id text,
  order_reference text,
  status text not null default 'active',      -- 'active' | 'refunded'
  created_at timestamptz not null default now(),
  unique (user_id, product_slug, stripe_session_id)
);

create index if not exists entitlements_user_idx on public.entitlements(user_id);
create index if not exists entitlements_email_idx on public.entitlements(customer_email);

-- 3) RLS
alter table public.profiles enable row level security;
alter table public.entitlements enable row level security;

-- Profils : chacun lit/modifie le sien ; le service role gère tout.
drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles self upsert" on public.profiles;
create policy "profiles self upsert" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "service role manages profiles" on public.profiles;
create policy "service role manages profiles" on public.profiles
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- Entitlements : l'utilisateur lit les siens ; seul le service role (webhook) écrit.
drop policy if exists "entitlements self read" on public.entitlements;
create policy "entitlements self read" on public.entitlements
  for select using (auth.uid() = user_id);

drop policy if exists "service role manages entitlements" on public.entitlements;
create policy "service role manages entitlements" on public.entitlements
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

-- 4) Création automatique du profil à l'inscription
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, first_name, last_name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name',
    coalesce(new.raw_user_meta_data ->> 'role', 'buyer')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
